// beagle/generate/scaffold/src/formula/web-generator/_vendor/beagle-react/src/App.tsx
import React from 'react';
import './App.css';
import { BeagleProvider, BeagleRemoteView } from '@zup-it/beagle-react';
import BeagleService from './beagle/beagle-service';

function App() {
  return (
    <BeagleProvider value={BeagleService}>
      <BeagleRemoteView path={'/screen'} />
    </BeagleProvider>
  );
}

export default App;

// beagle/generate/scaffold/src/formula/web-generator/beagle-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { LoadParams } from '@zup-it/beagle-web';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'beagleWeb';

  loadParams: LoadParams;

  constructor() {
    this.loadParams = {
      path: '/screen'
    };
  }
}
